# Generated by Django 4.2.21 on 2025-06-02 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('pw', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('nickName', models.CharField(max_length=100)),
                ('tel', models.CharField(default='010-0000-0000', max_length=100)),
                ('gender', models.CharField(default='여자', max_length=100)),
                ('hobby', models.CharField(default='게임', max_length=100)),
                ('mdate', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
