# Generated by Django 4.2.21 on 2025-05-27 03:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='rdate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 5, 27, 12, 51, 3, 717270)),
        ),
    ]
