# Generated by Django 4.2.21 on 2025-05-27 03:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_alter_event_rdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='rdate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 5, 27, 12, 55, 37, 951232)),
        ),
    ]
