# Generated by Django 4.2.21 on 2025-06-20 01:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('bno', models.AutoField(primary_key=True, serialize=False)),
                ('btitle', models.CharField(max_length=1000)),
                ('bcontent', models.TextField(blank=True)),
                ('bgroup', models.IntegerField(default=0)),
                ('bstep', models.IntegerField(default=0)),
                ('bindent', models.IntegerField(default=0)),
                ('bhit', models.IntegerField(default=0)),
                ('bfile1', models.ImageField(blank=True, null=True, upload_to='board')),
                ('bfile2', models.ImageField(blank=True, null=True, upload_to='board')),
                ('ntchk', models.IntegerField(default=0)),
                ('bdate', models.DateTimeField(auto_now=True)),
                ('member', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='member.member')),
            ],
        ),
    ]
