# Generated by Django 4.2.21 on 2025-06-20 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='bfile1',
            field=models.ImageField(blank=True, null=True, upload_to='customer'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='bfile2',
            field=models.ImageField(blank=True, null=True, upload_to='customer'),
        ),
    ]
