# Generated by Django 4.2.21 on 2025-05-29 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_student_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='hobby',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
