# Generated by Django 4.2.21 on 2025-05-29 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('no', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('major', models.CharField(max_length=100)),
                ('age', models.IntegerField(default=0)),
                ('grade', models.IntegerField(default=0)),
                ('gender', models.CharField(max_length=10)),
                ('memo', models.TextField(blank=True, max_length=1000)),
                ('sdate', models.DateField(auto_now=True)),
            ],
        ),
    ]
