# Generated by Django 4.2.21 on 2025-06-04 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_alter_board_bfile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='board',
            old_name='bintent',
            new_name='bindent',
        ),
    ]
