# Generated by Django 4.2.21 on 2025-06-05 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0004_rename_bintent_board_bindent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='bfile',
            field=models.ImageField(blank=True, null=True, upload_to='board'),
        ),
    ]
